apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ccc
  template:
    metadata:
      labels:
        app: ccc
    spec:
      containers:
        - name: main
          image: ondrejsika/training-example-dhl
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 20Mi