apiVersion: apps/v1
kind: Deployment
metadata:
  name: eee
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eee
  template:
    metadata:
      labels:
        app: eee
    spec:
      containers:
        - name: main
          image: ondrejsika/training-example
          env:
            - name: PORT
              value: '80'
            - name: PORT_METRICS
              value: '80'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 20Mi