apiVersion: apps/v1
kind: Deployment
metadata:
  name: fff
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fff
  template:
    metadata:
      labels:
        app: fff
    spec:
      containers:
        - name: main
          image: ondrejsika/training-example
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 1Mi
            limits:
              cpu: 20m
              memory: 2Mi